version: "3.9"
services:
  frontend:
    image: totoki/frontend-clock
  backend:
    image: totoki/backend-clock
  gateway:
    image: totoki/gateway-clock
    depends_on:
    - "frontend"
    - "backend"
    ports:
    - "80:80"